import { defineConfig } from 'astro/config';
import vercel from '@astrojs/vercel/static';

// Static output is enough — all per-domain pages are pre-rendered. We use
// vercel.json (generated by scripts/build-vercel-config.mjs) to route each
// custom domain to its /sites/<domain>/ or /_directories/<domain>/ path.
export default defineConfig({
  output: 'static',
  adapter: vercel(),
  trailingSlash: 'always',
});
